name: pciquiz1
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  faker:
  intl:
  freezed_annotation:
  json_annotation: ^4.0.1
#   path: ^1.8.0

dev_dependencies:
  build_runner: ^2.0.0
  freezed: ^2.0.0
  json_serializable:
  lints: ^2.0.0
  test: ^1.16.0
